// =============================================================================
// Virtual DOM Node Types
// =============================================================================
// Platform-independent types that describe the virtual DOM tree.
// These types form an Abstract Syntax Tree (AST) that can be interpreted
// by different renderers (browser WASM, server-side rendering, test).
//
// Every node carries a string Id for stable identity across renders.
// IDs are generated at compile time by the Praefixum source generator,
// ensuring deterministic, zero-cost identification for efficient diffing.
//
// The type hierarchy:
//   Node(Id)
//   ├── Element(Id, Tag, Attributes, Children)
//   ├── Text(Id, Value)
//   ├── RawHtml(Id, Html)
//   ├── Memo<TKey>(Id, Key, CachedNode)
//   ├── LazyMemo<TKey>(Id, Key, Factory, CachedNode?)
//   └── Empty()
//
// Document(Title, Body, Head) wraps the root Node with page-level metadata.
// =============================================================================

namespace Abies.DOM;

/// <summary>
/// A complete document with title, body content, and optional head elements.
/// </summary>
/// <param name="Title">The page title.</param>
/// <param name="Body">The body content as a virtual DOM tree.</param>
/// <param name="Head">Optional managed head elements (meta, link, script, base).</param>
public record Document(string Title, Node Body, params HeadContent[] Head);

/// <summary>
/// Base type for all virtual DOM nodes. Every node carries a stable <paramref name="Id"/>
/// for efficient diffing and DOM addressing.
/// </summary>
/// <param name="Id">Unique identifier, typically generated by Praefixum at compile time.</param>
public record Node(string Id);

/// <summary>
/// An HTML element with a tag name, attributes, and children.
/// </summary>
/// <param name="Id">Unique identifier for this element.</param>
/// <param name="Tag">The HTML tag name (e.g., "div", "button", "input").</param>
/// <param name="Attributes">The element's attributes and event handlers.</param>
/// <param name="Children">The element's child nodes.</param>
public record Element(string Id, string Tag, Attribute[] Attributes, params Node[] Children) : Node(Id);

/// <summary>
/// A text node containing a string value.
/// </summary>
/// <param name="Id">Unique identifier for this text node.</param>
/// <param name="Value">The text content.</param>
public record Text(string Id, string Value) : Node(Id)
{
    /// <summary>Implicit conversion from Text to string.</summary>
    public static implicit operator string(Text text) => text.Value;

    /// <summary>Implicit conversion from string to Text (uses the string as both Id and Value).</summary>
    public static implicit operator Text(string text) => new(text, text);
}

/// <summary>
/// A raw (unprocessed) HTML node. Inserted as-is — no encoding or escaping.
/// Use with caution: the content is NOT sanitized.
/// </summary>
/// <param name="Id">Unique identifier for this node.</param>
/// <param name="Html">The raw HTML content.</param>
public record RawHtml(string Id, string Html) : Node(Id);

/// <summary>
/// An empty node — renders nothing. Used as a sentinel in diff
/// (e.g., when an old tree has a child that the new tree does not).
/// </summary>
public record Empty() : Node("");

// =============================================================================
// Memoization
// =============================================================================
// Memo and LazyMemo enable skipping subtree diffing when the key hasn't changed.
// This is the equivalent of Elm's `lazy` function.
//
// - Memo<TKey>: eager — the CachedNode is always materialized.
// - LazyMemo<TKey>: lazy — the Factory is only called if the key differs.
//
// Both use generic EqualityComparer<TKey> to avoid boxing for value types.
// =============================================================================

/// <summary>
/// Interface for memoized nodes — enables polymorphic key comparison
/// in the diff algorithm without reflection (trim-safe for WASM).
/// </summary>
public interface MemoNode
{
    /// <summary>The memo key used to determine if the node should be re-rendered.</summary>
    object MemoKey { get; }

    /// <summary>The actual node content to render.</summary>
    Node CachedNode { get; }

    /// <summary>Creates a new memo node with the same key but different cached content.</summary>
    Node WithCachedNode(Node newCachedNode);

    /// <summary>
    /// Compares memo keys without boxing overhead.
    /// Uses generic EqualityComparer for value types to avoid allocation.
    /// </summary>
    bool MemoKeyEquals(MemoNode other);
}

/// <summary>
/// A memoized node. When diffing, if the memo key equals the previous key,
/// the cached node is reused without re-diffing the subtree.
/// </summary>
/// <typeparam name="TKey">The type of the memo key (must implement proper equality).</typeparam>
/// <param name="Id">Unique identifier for this node.</param>
/// <param name="Key">The memo key — if equal to the previous key, the cached node is reused.</param>
/// <param name="CachedNode">The actual node content to render.</param>
public record Memo<TKey>(string Id, TKey Key, Node CachedNode) : Node(Id), MemoNode where TKey : notnull
{
    /// <inheritdoc/>
    object MemoNode.MemoKey => Key;

    /// <inheritdoc/>
    public Node WithCachedNode(Node newCachedNode) => this with { CachedNode = newCachedNode };

    /// <inheritdoc/>
    public bool MemoKeyEquals(MemoNode other) =>
        other is Memo<TKey> otherMemo &&
        EqualityComparer<TKey>.Default.Equals(Key, otherMemo.Key);
}

/// <summary>
/// Interface for lazy memoized nodes that defer evaluation until needed.
/// The factory function is only called if the key differs from the previous render.
/// </summary>
public interface LazyMemoNode
{
    /// <summary>The memo key used to determine if the node should be re-rendered.</summary>
    object MemoKey { get; }

    /// <summary>The cached node content (null if not yet evaluated).</summary>
    Node? CachedNode { get; }

    /// <summary>Evaluates the lazy function to produce the node content.</summary>
    Node Evaluate();

    /// <summary>Creates a new lazy memo with the cached content populated.</summary>
    Node WithCachedNode(Node cachedNode);

    /// <summary>
    /// Compares memo keys without boxing overhead.
    /// Uses generic EqualityComparer for value types to avoid allocation.
    /// </summary>
    bool MemoKeyEquals(LazyMemoNode other);
}

/// <summary>
/// A lazily-evaluated memoized node. Unlike <see cref="Memo{TKey}"/>,
/// the node content is NOT created until actually needed. During diffing,
/// if the key matches the previous key, the factory is never called.
/// This is the true performance benefit of Elm's <c>lazy</c> function.
/// </summary>
/// <typeparam name="TKey">The type of the memo key.</typeparam>
/// <param name="Id">Unique identifier for this node.</param>
/// <param name="Key">The memo key — if equal, the factory is skipped.</param>
/// <param name="Factory">The function that produces the node content (only called if key differs).</param>
/// <param name="CachedNode">The cached node content after evaluation (null initially).</param>
public record LazyMemo<TKey>(string Id, TKey Key, Func<Node> Factory, Node? CachedNode = null)
    : Node(Id), LazyMemoNode where TKey : notnull
{
    /// <inheritdoc/>
    object LazyMemoNode.MemoKey => Key;

    /// <inheritdoc/>
    Node? LazyMemoNode.CachedNode => CachedNode;

    /// <inheritdoc/>
    public Node Evaluate() => Factory();

    /// <inheritdoc/>
    public Node WithCachedNode(Node cachedNode) => this with { CachedNode = cachedNode };

    /// <inheritdoc/>
    public bool MemoKeyEquals(LazyMemoNode other) =>
        other is LazyMemo<TKey> otherLazy &&
        EqualityComparer<TKey>.Default.Equals(Key, otherLazy.Key);
}
